### ISSUE TITLE
Add ssh_user in config

### ISSUE THREAD

**Issue by Remiii** [Remiii/remiii-ansible-ubuntu-app-simple-symfony#11]
```
- hosts: '{{ hosts }}'
  remote_user: '{{ user }}'

  tasks:
     - ...
```
